### ISSUE TITLE
SSH error

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#298]
SSHエラーが発生するケースがある。発生確率は低い

```
Error in JobSubmitter: #<Errno::ECONNRESET: Connection reset by peer>
"~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/transport/server_version.rb:47:in `readpartial'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/transport/server_version.rb:47:in `block (2 levels) in negotiate!'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/transport/server_version.rb:45:in `loop'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/transport/server_version.rb:45:in `block in negotiate!'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/transport/server_version.rb:43:in `loop'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/transport/server_version.rb:43:in `negotiate!'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/transport/server_version.rb:32:in `initialize'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/transport/session.rb:84:in `new'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/transport/session.rb:84:in `block in initialize'"
 "/usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout'"
 "/usr/lib/ruby/1.9.1/timeout.rb:100:in `timeout'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/transport/session.rb:84:in `initialize'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh.rb:200:in `new'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh.rb:200:in `start'"
 "~/oacis/oacis/app/models/host.rb:116:in `start_ssh'"
 "~/oacis/oacis/app/workers/job_submitter.r:
.1/gems/mongoid-3.1.6/lib/mongoid/contextual/mongo.rb:640:in `yield_document'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.6/lib/mongoid/contextual/mongo.rb:123:in `block (2 levels) in each'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/moped-1.5.2/lib/moped/query.rb:77:in `block in each'"\n"~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/moped-1.5.2/lib/moped/cursor.rb:26:in `block in each'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/moped-1.5.2/lib/moped/cursor.rb:26:in `each'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/moped-1.5.2/lib/moped/cursor.rb:26:in `each'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/moped-1.5.2/lib/moped/query.rb:76:in `each'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/moped-1.5.2/lib/moped/query.rb:76:in `each'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.6/lib/mongoid/contextual/mongo.rb:122:in `block in each'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.6/lib/mongoid/contextual/mongo.rb:619:in `selecting'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.6/lib/mongoid/contextual/mongo.rb:121:in `each'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.6/lib/mongoid/contextual.rb:19:in `each'"
 "~/oacis/oacis/app/workers/job_submitter.rb:5:in `perform'"
 "~/oacis/oacis/app/workers/job_worker.rb:20:in `block in start'"
 "~/oacis/oacis/app/workers/job_worker.rb:19:in `loop'"
 "~/oacis/oacis/app/workers/job_worker.rb:19:in `start'"
 "~/oacis/oacis/vendor/bundle/ruby/1.9.1/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:51:in `block in start'"

**Comment by takeshi-uchitane** [comment]
#325で対応．閉じる．
