### ISSUE TITLE
CLI create_analyses says an error if number of target runs is 417240

### ISSUE THREAD

**Issue by takeshi-uchitane** [crest-cassia/oacis#497]
No analysis is created

```
Analysis.where(analyzer_id: "58108075058ec6363e7199a1").count
=> 0
```

Error message

```
./bin/oacis_cli create_analyses -a 58108075058ec6363e7199a1 -j job_parameter.json -o analysis_ids.json -t run_ids.json 
/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongo-2.3.0/lib/mongo/operation/result.rb:256:in `validate!': Cursor not found. (Mongo::Error::OperationFailure)
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongo-2.3.0/lib/mongo/operation/executable.rb:37:in `block in execute'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongo-2.3.0/lib/mongo/server/connection_pool.rb:107:in `with_connection'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongo-2.3.0/lib/mongo/server.rb:231:in `with_connection'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongo-2.3.0/lib/mongo/operation/executable.rb:35:in `execute'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongo-2.3.0/lib/mongo/cursor.rb:188:in `block in get_more'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongo-2.3.0/lib/mongo/retryable.rb:51:in `call'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongo-2.3.0/lib/mongo/retryable.rb:51:in `read_with_retry'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongo-2.3.0/lib/mongo/cursor.rb:187:in `get_more'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongo-2.3.0/lib/mongo/cursor.rb:113:in `each'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongo-2.3.0/lib/mongo/collection/view/iterable.rb:44:in `each'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.4/lib/mongoid/query_cache.rb:207:in `each'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.4/lib/mongoid/contextual/mongo.rb:121:in `each'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.4/lib/mongoid/contextual.rb:20:in `each'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.4/lib/mongoid/relations/targets/enumerable.rb:182:in `each'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-5.1.4/lib/mongoid/relations/referenced/many.rb:165:in `each'
	from /home/oacis/oacis/lib/cli/oacis_cli_analysis.rb:65:in `block in create_analyses'
	from /home/oacis/oacis/lib/cli/oacis_cli_analysis.rb:64:in `each'
	from /home/oacis/oacis/lib/cli/oacis_cli_analysis.rb:64:in `create_analyses'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from ./bin/oacis_cli:7:in `<main>'

```

**Comment by takeshi-uchitane** [comment]
The error does not occur when the number of target run is one.
But, it takes 1min. or more to see the progress bar.
`Progress =============================================== 100% (1/1)`

**Comment by yohm** [comment]
Since this is a MongoDB issue, I cannot figure out how to fix it. For the moment, please avoid making such a large number of analyses.
