### ISSUE TITLE
Parameters An identical parameters already exists

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#655]
Watcher を実行中、以下のエラーで止まってしまった。
Watcher では、同じパラメータセットで投げてはだめ？
同じパラメータセットがあるかどうかをチェックできる？

    Traceback (most recent call last):
	13: from ./runMogaWatcherCwMates:139:in `<main>'
	12: from /home/oacis/work/iss/Oacis/docker/lib/MogaWatcher.rb:194:in `run'
	11: from /home/oacis/work/iss/Oacis/docker/lib/MogaWatcher.rb:228:in `alter'
	10: from /home/oacis/work/iss/Oacis/docker/lib/MogaWatcher.rb:252:in `alterOneByTournament4'
	 9: from /home/oacis/work/iss/Oacis/docker/lib/MogaWatcher.rb:330:in `newIndivsFromWinner'
	 8: from /home/oacis/work/iss/Oacis/docker/lib/MogaWatcher.rb:150:in `newIndiv'
	 7: from /home/oacis/work/iss/Oacis/docker/lib/MogaWatcher.rb:150:in `new'
	 6: from /home/oacis/work/iss/Oacis/docker/lib/MogaWatcher.rb:492:in `initialize'
	 5: from /home/oacis/work/iss/Oacis/docker/lib/MogaWatcher.rb:509:in `createPsAndRun'
	 4: from /home/oacis/work/iss/Oacis/docker/lib/SimulatorStub.rb:64:in `createPsAndRun'
	 3: from /home/oacis/oacis/app/models/simulator.rb:160:in `find_or_create_parameter_set'
	 2: from /home/oacis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mongoid-7.0.4/lib/mongoid/association/many.rb:68:in `create!'
	 1: from /home/oacis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mongoid-7.0.4/lib/mongoid/persistable/savable.rb:45:in `save!'
    /home/oacis/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mongoid-7.0.4/lib/mongoid/persistable.rb:76:in `fail_due_to_validation!':  (Mongoid::Errors::Validations)
    message:
      Validation of ParameterSet failed.
    summary:
      The following errors were found: Parameters An identical parameters already exists : 5df474774a32440de4ad2ddc
    resolution:
      Try persisting the document with valid data or remove the validations.`

**Comment by yohm** [comment]
@noda50 これもバグのようです。ご連絡ありがとうございます。

watcherであろうとなかろうと、同じパラメータをもつPSを複数作ることはできません。
`find_or_create_parameter_set` に期待される挙動としては、
- 同じparameterを持つPSがすでに存在していたら、そのPSを返す
- 存在していなかったら、新しくPSを作り、そのPSを返す

です。APIにべき等性を持たせ、ユーザー側で重複のチェックをする必要がないようになっています。
ここでは、たまたま既存のものと重複したようですが、その際に重複しているPSを返していないのでバグだと考えられます。調査してみます。

**Comment by noda50** [comment]
同じ現象で、これはバグと言えるかわからないが、
ParameterSet で、Host パラメータだけ変更したものが作れない。
例えば、ABCI では、"group" というパラメータを指定する必要があるが、この "group" は、ABCI を使う際に付与される user group (linux のユーザアカウントのgroup。ABCIでは予算に紐づけされている。）を指定する。この group を変更して投げたいときなど、うまく行かない。

**Comment by yohm** [comment]
HostParameter だけ変更したものが作れないというのは具体的にどういうことでしょうか？
期待される動作としては、Run作成時にUIからでもAPIからでもHostParameterを指定できるはずです。

**Comment by noda50** [comment]
１つの ParameterSet から Run 作る際に作れるのは、発見できました。
ただ、New Parameter Set で大量に生成する際に、Host Parameter 以外が同じだと、生成できない、という問題が、やはりあります。
